### ISSUE TITLE
I get a crash when my script are loading!

### ISSUE THREAD

**Issue by iMixSwag** [ensoulsharp-io/EnsoulSharp.Assemblies#10]
Why am I keep getting a crash when my scripts are loading? My DX9 mode is active and i have LoL video setting in borderless, what should I do?
More details about my problem:
When i start the game I can see "EnsoulSharp" on my top of the screen. After a few seconds i get my ezevade script loaded, then i get a crash. First thing i tought its because of the script so I deactivated all of them and just let the SDK one. And again it injected, my script was loaded, I can saw the range of my attacks but again it crashed. Please help!
Thanks!

**Comment by krisoft20** [comment]
https://www.mediafire.com/file/8n66za9u05o24d1/hotfix12.3_garena.rar/file

use hotfix, it means download that file from above, then login to the league client (be in main menu) and drag drop those 2 files to League of Legends/Game folder (you need to do it every time you login to the game because gave patch those files).

**Comment by alowmo** [comment]
> https://www.mediafire.com/file/8n66za9u05o24d1/hotfix12.3_garena.rar/file
> 
> use hotfix, it means download that file from above, then login to the league client (be in main menu) and drag drop those 2 files to League of Legends/Game folder (you need to do it every time you login to the game because gave patch those files).

NOT WORKING
